# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/intromicropy',
                'doc_host': 'https://nshea3.github.io',
                'git_url': 'https://github.com/nshea3/intromicropy',
                'lib_path': 'intromicropy'},
  'syms': {'intromicropy.core': {'intromicropy.core.foo': ('core.html#foo', 'intromicropy/core.py')}}}