# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/intromicropy',
                'doc_host': 'https://nshea3.github.io',
                'git_url': 'https://github.com/nshea3/intromicropy',
                'lib_path': 'intromicropy'},
  'syms': { 'intromicropy.core': { 'intromicropy.core.demand': ('core.html#demand', 'intromicropy/core.py'),
                                   'intromicropy.core.find_equilibrium': ('core.html#find_equilibrium', 'intromicropy/core.py'),
                                   'intromicropy.core.supply': ('core.html#supply', 'intromicropy/core.py')}}}